# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_filter = QtWidgets.QLabel(self.centralwidget)
        self.label_filter.setGeometry(QtCore.QRect(3, 7, 90, 20))
        self.label_filter.setObjectName("label_filter")
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_filter.setFont(font)

        self.label_blend_image = QtWidgets.QLabel(self.centralwidget)
        self.label_blend_image.setGeometry(QtCore.QRect(3, 227, 80, 16))
        self.label_blend_image.setObjectName("label_blend_image")
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_blend_image.setFont(font)

        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(3, 30, 120, 190))
        self.listView.setObjectName("listView")
        self.listView.addItem("None")
        self.listView.addItem("GreyScale")
        self.listView.addItem("Sharp ")
        self.listView.addItem("Sepia")
        self.listView.addItem("Pencil Sketch Effect (GreyScale)")
        self.listView.addItem("Pencil Sketch Effect (Colour)")
        self.listView.addItem("HDR")
        self.listView.addItem("Invert")
        self.listView.addItem("Summer")
        self.listView.addItem("Winter")
        self.listView.addItem("Cartoon")

        self.listView.setCurrentRow(0)

        self.listView2 = QtWidgets.QListWidget(self.centralwidget)
        self.listView2.setGeometry(QtCore.QRect(3, 250, 120, 190))
        self.listView2.setObjectName("listView2")
        self.listView2.addItem("None")
        self.listView2.addItem("Old 1")
        self.listView2.addItem("Old 1n ")
        self.listView2.addItem("Old 2")
        self.listView2.addItem("Old 2n")
        self.listView2.addItem("Old 3")
        self.listView2.addItem("Old 3n")
        self.listView2.addItem("Old 4")
        self.listView2.addItem("Old 4n")
        self.listView2.addItem("Old 5")
        self.listView2.addItem("Old 5n")
        self.listView2.addItem("Old 6")
        self.listView2.addItem("Old 6n")
        self.listView2.addItem("Old 7")
        self.listView2.addItem("Old 7n")
        self.listView2.setCurrentRow(0)

        self.showImage = QtWidgets.QLabel(self.centralwidget)
        self.showImage.setGeometry(QtCore.QRect(130, 3, 540, 360))
        self.showImage.setFrameShape(QtWidgets.QFrame.Box)
        self.showImage.setText("")
        self.showImage.setScaledContents(False)
        self.showImage.setObjectName("ShowImage")

        self.btnSelectImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectImage.setGeometry(QtCore.QRect(690, 10, 81, 31))
        self.btnSelectImage.setObjectName("btnSelectImage")

        self.btnSaveImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveImage.setGeometry(QtCore.QRect(690, 60, 81, 31))
        self.btnSaveImage.setObjectName("btnSaveImage")

        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(690, 110, 81, 31))
        self.btnReset.setObjectName("btnReset")

        self.slider_brightness = QtWidgets.QSlider(self.centralwidget)
        self.slider_brightness.setGeometry(QtCore.QRect(210, 380, 461, 22))
        self.slider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.slider_brightness.setMinimum(0)
        self.slider_brightness.setMaximum(500)
        self.slider_brightness.setValue(50)

        self.slider_blur = QtWidgets.QSlider(self.centralwidget)
        self.slider_blur.setGeometry(QtCore.QRect(210, 410, 461, 22))
        self.slider_blur.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blur.setObjectName("slider_blur")
        self.slider_blur.setMinimum(-1)
        self.slider_blur.setMaximum(100)
        self.slider_blur.setValue(-1)

        self.slider_vegnette = QtWidgets.QSlider(self.centralwidget)
        self.slider_vegnette.setGeometry(QtCore.QRect(210, 440, 461, 22))
        self.slider_vegnette.setOrientation(QtCore.Qt.Horizontal)
        self.slider_vegnette.setObjectName("slider_vegnette")
        self.slider_vegnette.setMinimum(99)
        self.slider_vegnette.setMaximum(500)
        self.slider_vegnette.setValue(99)

        self.label_brightness = QtWidgets.QLabel(self.centralwidget)
        self.label_brightness.setGeometry(QtCore.QRect(150, 380, 61, 16))
        self.label_brightness.setObjectName("label_brightness")

        self.label_blur = QtWidgets.QLabel(self.centralwidget)
        self.label_blur.setGeometry(QtCore.QRect(150, 410, 61, 16))
        self.label_blur.setObjectName("label_blur")

        self.label_vegnette = QtWidgets.QLabel(self.centralwidget)
        self.label_vegnette.setGeometry(QtCore.QRect(150, 440, 61, 16))
        self.label_vegnette.setObjectName("label_vegnette")

        self.slider_saturation = QtWidgets.QSlider(self.centralwidget)
        self.slider_saturation.setGeometry(QtCore.QRect(210, 470, 461, 22))
        self.slider_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.slider_saturation.setObjectName("slider_saturation")
        self.slider_saturation.setMinimum(-100)
        self.slider_saturation.setMaximum(100)
        self.slider_saturation.setValue(0)

        self.label_saturation = QtWidgets.QLabel(self.centralwidget)
        self.label_saturation.setGeometry(QtCore.QRect(150, 470, 61, 16))
        self.label_saturation.setObjectName("label_saturation")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Filter App"))
        self.btnSelectImage.setText(_translate("MainWindow", "Select Image"))
        self.btnSaveImage.setText(_translate("MainWindow", "Save"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.label_filter.setText(_translate("MainWindow", "Filter&Effect"))
        self.label_brightness.setText(_translate("MainWindow", "Brightness"))
        self.label_blur.setText(_translate("MainWindow", "Blur"))
        self.label_vegnette.setText(_translate("MainWindow", "Vignette"))
        self.label_saturation.setText(_translate("MainWindow", "Saturation"))
        self.label_blend_image.setText(_translate("MainWindow", "Old"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
